#服务器信息配置
server:
  port: 12231

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.77.11:3306/note?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: shisan@
#    url: jdbc:mysql://127.0.0.1:6066/shisan_note?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: liyishisan

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml