#服务器信息配置
server:
  port: 12230

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-ehywp1aw.sql.tencentcdb.com:23714/shisan_note?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: pasture
    password: pasture_1
#    url: jdbc:mysql://127.0.0.1:6066/shisan_note?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: liyishisan
  data:
    redis:
      host: 39.103.208.26
      port: 6380
      password: bAUG6IPdfrMWJlao
      database: 5
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml